### ISSUE TITLE
Does this plugin support Windows?

### ISSUE THREAD

**Issue by gefgef** [smerrill/vagrant-gatling-rsync#12]
Hi everybody! I install vagrant-gatling-rsync plugin without any problems to Win 7 x64, but seems it doesn't work here. When typing `vagrant gatling-rsync-auto` or `vagrant rsync` nothing happens. Command `vagrant provision` works fine, by the way.
My Vagrantfile looks like this (and works on Ubuntu, MacOS X too):

```
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.synced_folder "files", "/home/ec2", type: "rsync"

  if Vagrant.has_plugin?("vagrant-gatling-rsync")
    config.gatling.latency = 2.5
  end

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "xxx"
    aws.secret_access_key = "yyyy"
    aws.keypair_name = "zzzz"

    aws.ami = "ami-05ebd06c"

    override.ssh.username = "root"
    override.ssh.private_key_path = "pempem.pem"
  end
end
```

So, the question is, **does plugin work on Windows?**  Thanks!

**Comment by trompx** [comment]
Despite the new version of Vagrant, use of listen 2.7.12 which should improve speed, I don't see any improvement on my system (windows 8.1, Vagrant 2.7.1 : 3-8s in the VM for the watch to detect file changes). So I wanted to know if you still intend to release a new version with windows support ?

I tried to enable your plugin for window but I get the following error : 
listen/listenwindows.rb:21:in `watch_recursively': can't modify frozen String (RuntimeError)

Thank you
