### ISSUE TITLE
Failed to sync if gatling-rsync is started after making changes

### ISSUE THREAD

**Issue by droidlabour** [smerrill/vagrant-gatling-rsync#13]
gatling-rsync not able to pick/sync up file changes if it's started after making changes to a file that's being watched and which is already in sync using  gatling-rsync mentioned in VagrantFile.
Here's the sequence I'm using
1. vagrant up --provider=aws ec2
2. Save a file that's being watched
3. Start  gatling-rsync to watch that file
But it fails to pick up the changes to that file

I've to touch that file in order to make  gatling-rsync pick it up.

**Comment by smerrill** [comment]
This has been released to RubyGems as version 0.1.0.

https://rubygems.org/gems/vagrant-gatling-rsync/versions/0.1.0
