### ISSUE TITLE
Can this be made to use on real servers, not virtual/vagrant boxes?

### ISSUE THREAD

**Issue by michaelbutler** [smerrill/vagrant-gatling-rsync#22]
I really like this tool, with the local file watchers and event coalescing. Can it be used with real servers over ssh or scp, or are there comparable tools out there for this purpose? Thanks.

**Comment by smerrill** [comment]
I'm glad you enjoy vagrant-gatling-rsync!

I haven't tried it, but I think you could use https://github.com/tknerr/vagrant-managed-servers against other servers that are managed outside of Vagrant.
