### ISSUE TITLE
Two-way sync?

### ISSUE THREAD

**Issue by rogerrogers** [smerrill/vagrant-gatling-rsync#30]
This is a great plug-in, thanks!

Is there a way to configure two-way syncing like the default rsync for Vagrant?

**Comment by smerrill** [comment]
I don't think that Vagrant's default sync is two-way because of the difficulty involved.

**Comment by smerrill** [comment]
See https://github.com/mitchellh/vagrant/issues/3062 - this is still an open request. I wrote [vagrant-rsync-back](https://github.com/smerrill/vagrant-rsync-back) to allow a one-time sync back, but there's no built-in support for continual two-way sync.
