### ISSUE TITLE
Fedora 23 issue with libffi

### ISSUE THREAD

**Issue by tstella-ss** [smerrill/vagrant-gatling-rsync#31]
Hello there!

I'm having an issue with using vagrant-gatling-rsync on Fedora 23 -- when running it, it crashes with the following error:

```
/opt/vagrant/embedded/gems/gems/ffi-1.9.10/lib/ffi.rb:6:in `require': libffi.so.5: cannot open shared object file: No such file or directory - /opt/vagrant/embedded/gems/extensions/x86_64-linux/2.2.0/ffi-1.9.10/ffi_c.so (LoadError)
```

The `libffi` package is installed, but provides `libffi.so.6`:
```
root@host# rpm -ql libffi
/usr/lib64/libffi.so.6
/usr/lib64/libffi.so.6.0.2
/usr/share/doc/libffi
/usr/share/doc/libffi/README
/usr/share/licenses/libffi
/usr/share/licenses/libffi/LICENSE
```

I am on the latest version of the plugin `vagrant-gatling-rsync (0.9.0)`

Thanks,

Tim

**Comment by smerrill** [comment]
Tim,

I think this workaround may fix it: https://github.com/mitchellh/vagrant/issues/6721 .
